### ISSUE TITLE
how to use and run pls post video

### ISSUE THREAD

**Issue by Shanmugam031093** [lokesh1729/dream11-team-select#8]
my mail id is r.shanmugam6745@gmail.com

**Comment by Shanmugam031093** [comment]
Hi bro,

Could you please give updated file

**Comment by ritesh0313** [comment]
Hi friend,
Plz share how to use this script.

Thanks.

**Comment by lokesh1729** [comment]
Hi @ritesh0313 @Shanmugam031093 

I created this repo in 2017 , it used to work fine then, but it won't work now as dream11 had undergone many changes in web UI.
